### ISSUE TITLE
I tried the toy data but it failed in the first index steps, 

### ISSUE THREAD

**Issue by danessel** [moeinzadeh/Ranbow#2]

**Comment by danessel** [comment]
(ranbow) essel002@jacqueline-i:~/ranbow$ python ranbow.py hap -mode index -par ~/ranbow/toy/hap.params
[E::fai_build3_core] Failed to open the file ~/ranbow/toy/sel.fa
Traceback (most recent call last):
  File "ranbow.py", line 153, in <module>
    main(sys.argv[1:])
  File "ranbow.py", line 18, in main
    hap = haplotyper.haplotyper(argv, main_act)
  File "/media/bulk_01/users/essel002/ranbow/haplotyper.py", line 269, in __init__
    ps.faidx(self.ref)
  File "/media/bulk_01/users/essel002/anaconda3/envs/ranbow/lib/python2.7/site-packages/pysam/utils.py", line 75, in __call__
    stderr))
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=[faidx] Could not build fai index ~/ranbow/toy/sel.fa.fai\n'

**Comment by moeinzadeh** [comment]
Hi Danessel,
You can provide absolute path in the parameter file. Let me know if it works.
Best,
Hossein
