### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by elsasverris** [moeinzadeh/Ranbow#3]
Hi,
I am trying to use Ranbow on tetraploid potato. I have run the haplotyper (mode hap) on the toy example with success, but when I try it on my own data, I get an IndexError.

python ranbow.py hap -mode hap -par Kuras/params.txt -processorIndex 0
('ST4.03ch01', 1, 88663952, 'ST4.03ch01')
Traceback (most recent call last):
  File "ranbow.py", line 153, in <module>
    main(sys.argv[1:])
  File "ranbow.py", line 23, in main
    hap.go()
  File "/srv/KLN/users/esv/Ranbow/haplotyper.py", line 1897, in go
    self.haplotyping_change_for_ranbow_new(l_l_selected_scf[cpu_id])
  File "/srv/KLN/users/esv/Ranbow/haplotyper.py", line 1555, in haplotyping_change_for_ranbow_new
    vcf_info = self.indexingVCF(scf, self.vcf)
  File "/srv/KLN/users/esv/Ranbow/haplotyper.py", line 616, in indexingVCF
    l_cigar = tmp1[6][6:]. split(',')
IndexError: list index out of range

Can you see what the error is and how to fix it?

Best regards,
Elsa

**Comment by moeinzadeh** [comment]
Hi Elsa,

There are several IDs in the INFO tag column of each variant in a VCF file. Ranbow uses the CIGAR tag. I suppose you VCF file doesn't carry the CIGAR ID.

Best,
Hosssein

**Comment by schrins** [comment]
I ran into the same problem while trying to use ranbow on my own data. The VCF I got indeed does not have any cigar strings included (and I still have to find out to manually add them, because they should be computable from just the allele sequences for a specific variant). But even if the cigar strings were there, the software expects them to be at a hardcoded position (index 6), which might not apply to all datasets.
@elsasverris If you have a CIGAR field among the INFO tags in your VCF, you could as a workaround find out the index and change the line of code in haplotyper.py. Please note that you have to start counting from 0 to get the right index (so index 6from above actually refers to the 7th field, because the first field has index 0). The modified line should look something like

`l_cigar = tmp1[X][6:]. split(',')`

with X being the custom field index.

**Comment by moeinzadeh** [comment]
Hi schrins,
Thank you for the message. I developed Ranbow using freebayes as the variant caller, and it generates the CIGAR string for each variant. 
Regarding hardcoded position of CIGAR string, you are right. Thanks for suggestion a work around solution. I will try to fix this issue soon and push it again soon. 
best,
moeinzadeh

**Comment by moeinzadeh** [comment]
> I ran into the same problem while trying to use ranbow on my own data. The VCF I got indeed does not have any cigar strings included (and I still have to find out to manually add them, because they should be computable from just the allele sequences for a specific variant). But even if the cigar strings were there, the software expects them to be at a hardcoded position (index 6), which might not apply to all datasets. @elsasverris If you have a CIGAR field among the INFO tags in your VCF, you could as a workaround find out the index and change the line of code in haplotyper.py. Please note that you have to start counting from 0 to get the right index (so index 6from above actually refers to the 7th field, because the first field has index 0). The modified line should look something like
> 
> `l_cigar = tmp1[X][6:]. split(',')`
> 
> with X being the custom field index.

I fixed it. Thanks for mentioning this issue. The CIGAR tag can be located in any order in the info column of vcf file.
